name = "Yuan2"
license = "MIT"
licenselink = "https://github.com/marcsello/yuan2/blob/master/LICENSE"
description = "Minimalistic one-page theme for Hugo"
homepage = "https://github.com/marcsello/yuan2"
demosite = "https://ctrl-alt-gg.hu/"
tags = ["one-page", "simple", "clean", "dark", "minimalist", "lightweight", "no-js"]
features = ["responsive", "one-page", "social-icons", "darkmode", "seo", "no-js"]
min_version = "0.117.0"

[author]
    name = "Marcsello"
    homepage = "https://marcsello.com"
